### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by xnanodax** [Carly-Schaaf/AirBnb-Full-Stack-Clone#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
+ Let's MVP 4 with MVP 5 :) We'll build bookings first, then search! (Bookings is essential to airBnB!)
+ Typically for AirBnB, the CRUD cycle will be bookings! Feel free if you also want to have a CRUD cycle for listings as well :) 
+ Let's split booking and reviews into 2 MVPs. They are related but are pretty different components. We can list Users and Host Profiles as a Bonus MVP :)

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
+ You may need to add bathroom numbers, bed numbers, bedROOM numbers since AirBnB has these!
+ If you are planning on using the google maps api, consider adding a `longitude` and `latitude` coordinates in the listings schema.
+ AirBnB has a lot of information about each listing: ac? laundry machine? wifi? We should incorporate these as well into the schema.

Thank you for asking questions on the proposal!
+ We can break up `location` into `address_1`, `address_2`, `state`, `zipcode`, etc just like all the forms we've filled out on the internet. 
+ I agree `price` should be the price per night. We can rename his column to be `daily_rate` or `daily_price`. 
+ `owner_id` should be indexed so we can look up more quickly on the owner table :)

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
+ We could have a nested route when creating the booking. Instead of `POST /api/bookings`, we can have `POST /api/listings/:id/bookings` so we can pass the listing id through the url. Up to you :)
+ You should still have a `GET /api/bookings` for search so you can get booking results!

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by xnanodax** [comment]
Great job, Carly! I left my comments below each section! You can respond to this github issue for questions!

Comment back on this page so I can look it over. I will check off the boxes :)

**Comment by Carly-Schaaf** [comment]
#### RE: Database Schema - 

I added all of the amenities to the listings table that Airbnb offers. I chose to default these columns to false because Airbnb tells its guests to check which ones they *do* offer when making a listing. 

One question:
1. Should I include my location columns in addition to the `lat` & `lng` columns? I'm guessing I should.

How does the schema look?

Thanks!

**Comment by Carly-Schaaf** [comment]
I also fixed my MVPs! Or so I think! Let me know if not

**Comment by Carly-Schaaf** [comment]
#### RE: Backend Routes - 

You said "You should still have a GET /api/bookings for search so you can get booking results!" 

Do you mean when searching for a listing and filtering by availability? Otherwise, I was thinking that bookings would be a lot like your `GET likes` example, as I won't be rendering all bookings on their own but rather via the profile show page.

Otherwise, I think I addressed all of the concerns you raised!

**Comment by xnanodax** [comment]
`GET /api/bookings`
We'll use this backend route for the Trips page :)!

`GET /api/reviews` 
+ If you want to fetch all the reviews when fetching the listing, then you wont need this! 
+ If you want to fetch a small collection of reviews at a time (airbnb fetches the 7~8 newest reviews), then this would be necessary this route when fetching another set of reviews :)

**Comment by xnanodax** [comment]
Your proposal looks 💯 !
